// Copyright TiKV Project Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/tikv/tikv-operator/pkg/apis/tikv/v1alpha1"
	scheme "github.com/tikv/tikv-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TikvClustersGetter has a method to return a TikvClusterInterface.
// A group's client should implement this interface.
type TikvClustersGetter interface {
	TikvClusters(namespace string) TikvClusterInterface
}

// TikvClusterInterface has methods to work with TikvCluster resources.
type TikvClusterInterface interface {
	Create(*v1alpha1.TikvCluster) (*v1alpha1.TikvCluster, error)
	Update(*v1alpha1.TikvCluster) (*v1alpha1.TikvCluster, error)
	UpdateStatus(*v1alpha1.TikvCluster) (*v1alpha1.TikvCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TikvCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.TikvClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TikvCluster, err error)
	TikvClusterExpansion
}

// tikvClusters implements TikvClusterInterface
type tikvClusters struct {
	client rest.Interface
	ns     string
}

// newTikvClusters returns a TikvClusters
func newTikvClusters(c *TikvV1alpha1Client, namespace string) *tikvClusters {
	return &tikvClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tikvCluster, and returns the corresponding tikvCluster object, and an error if there is any.
func (c *tikvClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.TikvCluster, err error) {
	result = &v1alpha1.TikvCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tikvclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TikvClusters that match those selectors.
func (c *tikvClusters) List(opts v1.ListOptions) (result *v1alpha1.TikvClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TikvClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tikvclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tikvClusters.
func (c *tikvClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tikvclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a tikvCluster and creates it.  Returns the server's representation of the tikvCluster, and an error, if there is any.
func (c *tikvClusters) Create(tikvCluster *v1alpha1.TikvCluster) (result *v1alpha1.TikvCluster, err error) {
	result = &v1alpha1.TikvCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tikvclusters").
		Body(tikvCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tikvCluster and updates it. Returns the server's representation of the tikvCluster, and an error, if there is any.
func (c *tikvClusters) Update(tikvCluster *v1alpha1.TikvCluster) (result *v1alpha1.TikvCluster, err error) {
	result = &v1alpha1.TikvCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tikvclusters").
		Name(tikvCluster.Name).
		Body(tikvCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *tikvClusters) UpdateStatus(tikvCluster *v1alpha1.TikvCluster) (result *v1alpha1.TikvCluster, err error) {
	result = &v1alpha1.TikvCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tikvclusters").
		Name(tikvCluster.Name).
		SubResource("status").
		Body(tikvCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the tikvCluster and deletes it. Returns an error if one occurs.
func (c *tikvClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tikvclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tikvClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tikvclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tikvCluster.
func (c *tikvClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TikvCluster, err error) {
	result = &v1alpha1.TikvCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tikvclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
