// Copyright TiKV Project Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tikv/tikv-operator/pkg/apis/tikv/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTikvClusters implements TikvClusterInterface
type FakeTikvClusters struct {
	Fake *FakeTikvV1alpha1
	ns   string
}

var tikvclustersResource = schema.GroupVersionResource{Group: "tikv.org", Version: "v1alpha1", Resource: "tikvclusters"}

var tikvclustersKind = schema.GroupVersionKind{Group: "tikv.org", Version: "v1alpha1", Kind: "TikvCluster"}

// Get takes name of the tikvCluster, and returns the corresponding tikvCluster object, and an error if there is any.
func (c *FakeTikvClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.TikvCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tikvclustersResource, c.ns, name), &v1alpha1.TikvCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TikvCluster), err
}

// List takes label and field selectors, and returns the list of TikvClusters that match those selectors.
func (c *FakeTikvClusters) List(opts v1.ListOptions) (result *v1alpha1.TikvClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tikvclustersResource, tikvclustersKind, c.ns, opts), &v1alpha1.TikvClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TikvClusterList{ListMeta: obj.(*v1alpha1.TikvClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.TikvClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tikvClusters.
func (c *FakeTikvClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tikvclustersResource, c.ns, opts))

}

// Create takes the representation of a tikvCluster and creates it.  Returns the server's representation of the tikvCluster, and an error, if there is any.
func (c *FakeTikvClusters) Create(tikvCluster *v1alpha1.TikvCluster) (result *v1alpha1.TikvCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tikvclustersResource, c.ns, tikvCluster), &v1alpha1.TikvCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TikvCluster), err
}

// Update takes the representation of a tikvCluster and updates it. Returns the server's representation of the tikvCluster, and an error, if there is any.
func (c *FakeTikvClusters) Update(tikvCluster *v1alpha1.TikvCluster) (result *v1alpha1.TikvCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tikvclustersResource, c.ns, tikvCluster), &v1alpha1.TikvCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TikvCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTikvClusters) UpdateStatus(tikvCluster *v1alpha1.TikvCluster) (*v1alpha1.TikvCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tikvclustersResource, "status", c.ns, tikvCluster), &v1alpha1.TikvCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TikvCluster), err
}

// Delete takes name of the tikvCluster and deletes it. Returns an error if one occurs.
func (c *FakeTikvClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tikvclustersResource, c.ns, name), &v1alpha1.TikvCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTikvClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tikvclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TikvClusterList{})
	return err
}

// Patch applies the patch and returns the patched tikvCluster.
func (c *FakeTikvClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TikvCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tikvclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.TikvCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TikvCluster), err
}
