// Copyright TiKV Project Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	tikvv1alpha1 "github.com/tikv/tikv-operator/pkg/apis/tikv/v1alpha1"
	versioned "github.com/tikv/tikv-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tikv/tikv-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tikv/tikv-operator/pkg/client/listers/tikv/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TikvClusterInformer provides access to a shared informer and lister for
// TikvClusters.
type TikvClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TikvClusterLister
}

type tikvClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTikvClusterInformer constructs a new informer for TikvCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTikvClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTikvClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTikvClusterInformer constructs a new informer for TikvCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTikvClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TikvV1alpha1().TikvClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TikvV1alpha1().TikvClusters(namespace).Watch(options)
			},
		},
		&tikvv1alpha1.TikvCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *tikvClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTikvClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *tikvClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tikvv1alpha1.TikvCluster{}, f.defaultInformer)
}

func (f *tikvClusterInformer) Lister() v1alpha1.TikvClusterLister {
	return v1alpha1.NewTikvClusterLister(f.Informer().GetIndexer())
}
